site_name: Jawt
theme:
  name: mkdocs
  locale: en
  color_mode: auto
  user_color_mode_toggle: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - First Page: tutorial/first-page.md
    - Project Structure: getting-started/project-structure.md
  - JML:
    - Overview: jml/index.md
    - Pages: jml/pages.md
    - Components: jml/components.md
    - Modules: jml/modules.md
    - Scripting: jml/scripting.md
  - Architecture:
    - Overview: architecture/index.md
    - Workspace Layout: architecture/workspace.md
    - Project Types: architecture/project-types.md
  - Runtime:
    - Overview: runtime/index.md
  - Extensibility:
    - Overview: extensibility/index.md
  - Testing & Debugging:
    - Overview: testing/index.md
  - References:
    - Pages: references/pages.md
    - Components: references/components.md
    - CLI: references/cli.md
  - API:
    - Overview: api/index.md
    - Browser: api/browser.md
    - State: api/state.md
  - Resources:
    - Contributing: resources/contributing.md
    - FAQ: resources/faq.md
  - Miscellaneous:
    - Catch List: misc/catch-list.md
