name: Build JAWT

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install cross-compilers
        run: sudo apt-get update && sudo apt-get install -y gcc-mingw-w64

      - name: Setup Parser
        run: make generate-parser

      - name: Build Linux amd64
        run: make build-linux-amd64

      - name: Build Linux arm64
        run: make build-linux-arm64

      - name: Build Windows amd64
        run: make build-windows-amd64

      - name: Build Windows arm64
        run: make build-windows-arm64

      - name: Build macOS amd64
        run: make build-macos-amd64

      - name: Build macOS arm64
        run: make build-macos-arm64

      - name: Upload build artefacts
        uses: actions/upload-artifact@v4
        with:
          name: jawt-binaries
          path: build/bin/
