name: Release JAWT Binaries

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0

permissions:
  contents: write  # Required for creating releases and uploading assets

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for GoReleaser to generate changelog

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Setup Parser
        run: make generate-parser

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}