name: Test JAWT

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Setup Parser
        run: make generate-parser

      - name: Run tests
        run: make test
